[package]
name = "a07_file_dialog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.24.1", features = ["__screenshot"] }
env_logger = "0.10.1"
rfd = "0.12.1"
